export default function Dados(){
    return ([
        {
            "id": 1,
            "crawled_at": "11/17/2019, 23:18:09",
            "description": "\n            Indiana Jones (Harrison Ford) is no ordinary archeologist. When we first see him, he is somewhere in the Peruvian jungle in 1936, running a booby-trapped gauntlet (complete with an over-sized rolling boulder) to fetch a solid-gold idol. He loses this artifact to his chief rival, a French archeologist named Belloq (Paul Freeman), who then prepares to kill our hero. In the first of many serial-like escapes, Indy eludes Belloq by hopping into a convenient plane. So, then: is Indiana Jones afraid of anything? Yes, snakes. The next time we see Jones, he's a soft-spoken, bespectacled professor. He is then summoned from his ivy-covered environs by Marcus Brody (Denholm Elliott) to find the long-lost Ark of the Covenant. The Nazis, it seems, are already searching for the Ark, which the mystical-minded Hitler hopes to use to make his stormtroopers invincible. But to find the Ark, Indy must first secure a medallion kept under the protection of Indy's old friend Abner Ravenwood, whose daughter, Marion (Karen Allen), evidently has a \"history\" with Jones. Whatever their personal differences, Indy and Marion become partners in one action-packed adventure after another, ranging from wandering the snake pits of the Well of Souls to surviving the pyrotechnic unearthing of the sacred Ark. A joint project of Hollywood prodigies George Lucas and Steven Spielberg, with a script co-written by Lawrence Kasdan and Philip Kaufman, among others, Raiders of the Lost Ark is not so much a movie as a 115-minute thrill ride. Costing 22 million dollars (nearly three times the original estimate), Raiders of the Lost Ark reaped 200 million dollars during its first run. It was followed by Indiana Jones and the Temple of Doom (1985) and Indiana Jones and the Last Crusade (1989), as well as a short-lived TV-series \"prequel.\"        ",
            "title": "Raiders of the Lost Ark",
            "url": "https://www.allmovie.com/movie/raiders-of-the-lost-ark-v40118",
            "poster": "https://cps-static.rovicorp.com/2/Open/CinemaSource/Indiana%20Jones%20and%20The%20Raiders%20of%20the%20Lost%20Ark%20%20The%20IMAX%20Experience/_derived_jpg_q90_600x800_m0/140449R1_CR.jpg",
            "raw_description": "\u003cdiv class=\"text\" itemprop=\"description\"\u003e\n            Indiana Jones (\u003ca href=\"https://www.allmovie.com/artist/harrison-ford-p24238\" class=\"name-link\"\u003eHarrison Ford\u003c/a\u003e) is no ordinary archeologist. When we first see him, he is somewhere in the Peruvian jungle in 1936, running a booby-trapped gauntlet (complete with an over-sized rolling boulder) to fetch a solid-gold idol. He loses this artifact to his chief rival, a French archeologist named Belloq (Paul Freeman), who then prepares to kill our hero. In the first of many serial-like escapes, Indy eludes Belloq by hopping into a convenient plane. So, then: is Indiana Jones afraid of anything? Yes, snakes. The next time we see Jones, he's a soft-spoken, bespectacled professor. He is then summoned from his ivy-covered environs by Marcus Brody (\u003ca href=\"https://www.allmovie.com/artist/denholm-elliott-p21589\" class=\"name-link\"\u003eDenholm Elliott\u003c/a\u003e) to find the long-lost Ark of the Covenant. The Nazis, it seems, are already searching for the Ark, which the mystical-minded \u003ca href=\"https://www.allmovie.com/artist/hitler-p366810\" class=\"name-link\"\u003eHitler\u003c/a\u003e hopes to use to make his stormtroopers invincible. But to find the Ark, Indy must first secure a medallion kept under the protection of Indy's old friend Abner Ravenwood, whose daughter, Marion (\u003ca href=\"https://www.allmovie.com/artist/karen-allen-p1033\" class=\"name-link\"\u003eKaren Allen\u003c/a\u003e), evidently has a \"history\" with Jones. Whatever their personal differences, Indy and Marion become partners in one action-packed adventure after another, ranging from wandering the snake pits of the Well of Souls to surviving the pyrotechnic unearthing of the sacred Ark. A joint project of Hollywood prodigies \u003ca href=\"https://www.allmovie.com/artist/george-lucas-p100308\" class=\"name-link\"\u003eGeorge Lucas\u003c/a\u003e and \u003ca href=\"https://www.allmovie.com/artist/steven-spielberg-p112325\" class=\"name-link\"\u003eSteven Spielberg\u003c/a\u003e, with a script co-written by \u003ca href=\"https://www.allmovie.com/artist/lawrence-kasdan-p96824\" class=\"name-link\"\u003eLawrence Kasdan\u003c/a\u003e and \u003ca href=\"https://www.allmovie.com/artist/philip-kaufman-p96903\" class=\"name-link\"\u003ePhilip Kaufman\u003c/a\u003e, among others, Raiders of the Lost Ark is not so much a movie as a 115-minute thrill ride. Costing 22 million dollars (nearly three times the original estimate), Raiders of the Lost Ark reaped 200 million dollars during its first run. It was followed by Indiana Jones and the Temple of Doom (1985) and Indiana Jones and the Last Crusade (1989), as well as a short-lived TV-series \"prequel.\"        \u003c/div\u003e",
            "produced_by": "na",
            "directed_by": "Steven Spielberg"
        },
        {
            "id": 2,
            "crawled_at": "11/17/2019, 23:18:09",
            "description": "\n            John Huston's 1948 treasure-hunt classic begins as drifter Fred C. Dobbs (Humphrey Bogart), down and out in Tampico, Mexico, impulsively spends his last bit of dough on a lottery ticket. Later on, Dobbs and fellow indigent Curtin (Tim Holt) seek shelter in a cheap flophouse and meet Howard (Walter Huston), a toothless, garrulous old coot who regales them with stories about prospecting for gold. Forcibly collecting their pay from their shifty boss, Dobbs and Curtin combine this money with Dobbs's unexpected windfall from a lottery ticket and, together with Howard, buy the tools for a prospecting expedition. Dobbs has pledged that anything they dig up will be split three ways, but Howard, who's heard that song before, doesn't quite swallow this. As the gold is mined and measured, Dobbs grows increasingly paranoid and distrustful, and the men gradually turn against each other on the way toward a bitterly ironic conclusion. The Treasure of the Sierra Madre is a superior morality play and one of the best movie treatments of the corrosiveness of greed.  Huston keeps a typically light and entertaining touch despite the strong theme, for which he won Oscars for both Director and Screenplay, as well as a supporting award for his father Walter, making Walter, John, and Anjelica Huston the only three generations of one family all to win Oscars.        ",
            "title": "The Treasure of the Sierra Madre",
            "url": "https://www.allmovie.com/movie/the-treasure-of-the-sierra-madre-v50884",
            "poster": "https://cps-static.rovicorp.com/2/Open/Turner%20Classic%20Movies/The%20Treasure%20of%20the%20Sierra%20Madre/_derived_jpg_q90_500x500_m0/TreasureOfTheSierraMadre_PosterArt1.jpg",
            "raw_description": "\u003cdiv class=\"text\" itemprop=\"description\"\u003e\n            \u003ca href=\"https://www.allmovie.com/artist/john-huston-p95260\" class=\"name-link\"\u003eJohn Huston\u003c/a\u003e's 1948 treasure-hunt classic begins as drifter Fred C. Dobbs (\u003ca href=\"https://www.allmovie.com/artist/humphrey-bogart-p7027\" class=\"name-link\"\u003eHumphrey Bogart\u003c/a\u003e), down and out in Tampico, Mexico, impulsively spends his last bit of dough on a lottery ticket. Later on, Dobbs and fellow indigent Curtin (\u003ca href=\"https://www.allmovie.com/artist/tim-holt-p33051\" class=\"name-link\"\u003eTim Holt\u003c/a\u003e) seek shelter in a cheap flophouse and meet Howard (\u003ca href=\"https://www.allmovie.com/artist/walter-huston-p34142\" class=\"name-link\"\u003eWalter Huston\u003c/a\u003e), a toothless, garrulous old coot who regales them with stories about prospecting for gold. Forcibly collecting their pay from their shifty boss, Dobbs and Curtin combine this money with Dobbs's unexpected windfall from a lottery ticket and, together with Howard, buy the tools for a prospecting expedition. Dobbs has pledged that anything they dig up will be split three ways, but Howard, who's heard that song before, doesn't quite swallow this. As the gold is mined and measured, Dobbs grows increasingly paranoid and distrustful, and the men gradually turn against each other on the way toward a bitterly ironic conclusion. The Treasure of the Sierra Madre is a superior morality play and one of the best movie treatments of the corrosiveness of greed.  Huston keeps a typically light and entertaining touch despite the strong theme, for which he won Oscars for both Director and Screenplay, as well as a supporting award for his father Walter, making Walter, John, and \u003ca href=\"https://www.allmovie.com/artist/anjelica-huston-p34131\" class=\"name-link\"\u003eAnjelica Huston\u003c/a\u003e the only three generations of one family all to win Oscars.        \u003c/div\u003e",
            "produced_by": "na",
            "directed_by": "John Huston"
        },
        {
            "id": 3,
            "crawled_at": "11/17/2019, 23:18:09",
            "description": "\n            Taiwanese filmmaker Ang Lee took a break from making Western period dramas to fashion this wild and woolly martial arts spectacular featuring special effects and action sequences courtesy of the choreographer of The Matrix (1999), Yuen Woo Ping. In the early 19th century, martial arts master Li Mu Bai (Chow Yun-Fat) is about to retire and enter a life of meditation, though he quietly longs to avenge the death of his master, who was killed by Jade Fox (Cheng Pei-pei). He gives his sword, a fabled 400-year-old weapon known as Green Destiny, to his friend, fellow martial arts wizard and secret love Yu Shu Lien (Michelle Yeoh), so that she may deliver it to Sir Te (Sihung Lung). Upon arrival in Peking, Yu happens upon Jen (Zhang Ziyi), a vivacious, willful politician's daughter. That night, a mysterious masked thief swipes Green Destiny, with Yu in hot pursuit -- resulting in the first of several martial arts action set pieces during the film. Li arrives in Beijing and eventually discovers that Jen is not only the masked thief but is also in cahoots with the evil Jade. In spite of this, Li sees great talent in Jen as a fighter and offers to school her in the finer points of martial arts and selflessness, an offer that Jen promptly rebukes. This film was first screened to much acclaim at the 2000 Cannes, Toronto, and New York film festivals and became a favorite when Academy Awards nominations were announced in 2001: Tiger snagged ten nods and later secured four wins for Best Cinematography, Score, Art Direction, and Foreign Language Film.        ",
            "title": "Crouching Tiger, Hidden Dragon",
            "url": "https://www.allmovie.com/movie/crouching-tiger-hidden-dragon-v201837",
            "poster": "https://cps-static.rovicorp.com/2/Open/Sony%20Pictures/Crouching%20Tiger%2c%20Hidden%20Dragon/_derived_jpg_q90_500x500_m0/crouc_katos_7_h.jpg",
            "raw_description": "\u003cdiv class=\"text\" itemprop=\"description\"\u003e\n            Taiwanese filmmaker \u003ca href=\"https://www.allmovie.com/artist/ang-lee-p166472\" class=\"name-link\"\u003eAng Lee\u003c/a\u003e took a break from making Western period dramas to fashion this wild and woolly martial arts spectacular featuring special effects and action sequences courtesy of the choreographer of \u003ca href=\"https://www.allmovie.com/movie/the-matrix-v177524\" class=\"movie-link\"\u003eThe Matrix\u003c/a\u003e (1999), \u003ca href=\"https://www.allmovie.com/artist/yuen-woo-ping-p194746\" class=\"name-link\"\u003eYuen Woo Ping\u003c/a\u003e. In the early 19th century, martial arts master Li Mu Bai (\u003ca href=\"https://www.allmovie.com/artist/chow-yun-fat-p22826\" class=\"name-link\"\u003eChow Yun-Fat\u003c/a\u003e) is about to retire and enter a life of meditation, though he quietly longs to avenge the death of his master, who was killed by Jade Fox (\u003ca href=\"https://www.allmovie.com/artist/cheng-pei-pei-p134191\" class=\"name-link\"\u003eCheng Pei-pei\u003c/a\u003e). He gives his sword, a fabled 400-year-old weapon known as Green Destiny, to his friend, fellow martial arts wizard and secret love Yu Shu Lien (\u003ca href=\"https://www.allmovie.com/artist/michelle-yeoh-p223709\" class=\"name-link\"\u003eMichelle Yeoh\u003c/a\u003e), so that she may deliver it to Sir Te (\u003ca href=\"https://www.allmovie.com/artist/sihung-lung-p197846\" class=\"name-link\"\u003eSihung Lung\u003c/a\u003e). Upon arrival in Peking, Yu happens upon Jen (\u003ca href=\"https://www.allmovie.com/artist/zhang-ziyi-p280898\" class=\"name-link\"\u003eZhang Ziyi\u003c/a\u003e), a vivacious, willful politician's daughter. That night, a mysterious masked thief swipes Green Destiny, with Yu in hot pursuit -- resulting in the first of several martial arts action set pieces during the film. Li arrives in Beijing and eventually discovers that Jen is not only the masked thief but is also in cahoots with the evil Jade. In spite of this, Li sees great talent in Jen as a fighter and offers to school her in the finer points of martial arts and selflessness, an offer that Jen promptly rebukes. This film was first screened to much acclaim at the 2000 Cannes, Toronto, and New York film festivals and became a favorite when Academy Awards nominations were announced in 2001: \u003ca href=\"https://www.allmovie.com/movie/tiger-v201837\" class=\"movie-link\"\u003eTiger\u003c/a\u003e snagged ten nods and later secured four wins for Best Cinematography, Score, Art Direction, and Foreign Language Film.        \u003c/div\u003e",
            "produced_by": "na",
            "directed_by": "Ang Lee"
        },
        {
            "id": 4,
            "crawled_at": "11/17/2019, 23:18:10",
            "description": "\n            It's Christmas time in L.A., and there's an employee party in progress on the 30th floor of the Nakatomi Corporation building. The revelry comes to a violent end when the partygoers are taken hostage by a group of terrorists headed by Hans Gruber (Alan Rickman), who plan to steal the 600 million dollars locked in Nakatomi's high-tech safe. In truth, Gruber and his henchmen are only pretending to be politically motivated to throw the authorities off track; also in truth, Gruber has no intention of allowing anyone to get out of the building alive. Meanwhile, New York cop John McClane (Bruce Willis) has come to L.A. to visit his estranged wife, Holly (Bonnie Bedelia), who happens to be one of the hostages. Disregarding the orders of the authorities surrounding the building, McClane, who fears nothing (except heights), takes on the villains, armed with one handgun and plenty of chutzpah. Until Die Hard came along, Bruce Willis was merely that wisecracking guy on Moonlighting. After the film's profits started rolling in, Willis found himself one of the highest-paid and most sought-after leading men in Hollywood.        ",
            "title": "Die Hard",
            "url": "https://www.allmovie.com/movie/die-hard-v13728",
            "poster": "https://cps-static.rovicorp.com/2/Open/20th%20Century%20Fox/Die%20Hard/_derived_jpg_q90_500x500_m0/DieHard-PosterArt.jpg",
            "raw_description": "\u003cdiv class=\"text\" itemprop=\"description\"\u003e\n            It's Christmas time in L.A., and there's an employee party in progress on the 30th floor of the Nakatomi Corporation building. The revelry comes to a violent end when the partygoers are taken hostage by a group of terrorists headed by Hans Gruber (Alan Rickman), who plan to steal the 600 million dollars locked in Nakatomi's high-tech safe. In truth, Gruber and his henchmen are only pretending to be politically motivated to throw the authorities off track; also in truth, Gruber has no intention of allowing anyone to get out of the building alive. Meanwhile, New York cop John McClane (\u003ca href=\"https://www.allmovie.com/artist/bruce-willis-p76618\" class=\"name-link\"\u003eBruce Willis\u003c/a\u003e) has come to L.A. to visit his estranged wife, Holly (\u003ca href=\"https://www.allmovie.com/artist/bonnie-bedelia-p4930\" class=\"name-link\"\u003eBonnie Bedelia\u003c/a\u003e), who happens to be one of the hostages. Disregarding the orders of the authorities surrounding the building, McClane, who fears nothing (except heights), takes on the villains, armed with one handgun and plenty of chutzpah. Until Die Hard came along, \u003ca href=\"https://www.allmovie.com/artist/bruce-willis-p76618\" class=\"name-link\"\u003eBruce Willis\u003c/a\u003e was merely that wisecracking guy on \u003ca href=\"https://www.allmovie.com/movie/moonlighting-v216960\" class=\"movie-link\"\u003eMoonlighting\u003c/a\u003e. After the film's profits started rolling in, \u003ca href=\"https://www.allmovie.com/artist/willis-p76618\" class=\"name-link\"\u003eWillis\u003c/a\u003e found himself one of the highest-paid and most sought-after leading men in Hollywood.        \u003c/div\u003e",
            "produced_by": "na",
            "directed_by": "John McTiernan"
        },
        {
            "id": 5,
            "crawled_at": "11/17/2019, 23:18:10",
            "description": "\n            In 1820s America, frontiersman and fur trapper Hugh Glass (Leonardo DiCaprio) and his teenage son Hawk (Forrest Goodluck) join a pelt-gathering expedition. However, their party are attacked by Arikara Native Americans, who kill a number of the men. Glass then tries to lead the remainder of the group to safety, charting a new path to a U.S. fort. Unfortunately, he is soon mauled by a grizzly bear while hunting for food, and is horribly wounded. He is left in the care of roughneck John Fitzgerald (Tom Hardy) and the young and inexperienced Jim Bridger (Will Poulter), while Hawk watches on in horror. Fitzgerald betrays him and leaves him buried alive in a shallow grave, but Glass nurses himself back to health and sets out to seek revenge. Alejandro González Iñárritu directed this pulse-pounding epic.        ",
            "title": "The Revenant",
            "url": "https://www.allmovie.com/movie/the-revenant-v597171",
            "poster": "https://cps-static.rovicorp.com/2/Open/20th_Century_Fox_39/Program/24045357/_derived_jpg_q90_500x500_m0/Revenant_1536x2048.jpg",
            "raw_description": "\u003cdiv class=\"text\" itemprop=\"description\"\u003e\n            In 1820s America, frontiersman and fur trapper Hugh Glass (\u003ca href=\"https://www.allmovie.com/artist/leonardo-dicaprio-p18926\" class=\"name-link\"\u003eLeonardo DiCaprio\u003c/a\u003e) and his teenage son Hawk (\u003ca href=\"https://www.allmovie.com/artist/forrest-goodluck-p814716\" class=\"name-link\"\u003eForrest Goodluck\u003c/a\u003e) join a pelt-gathering expedition. However, their party are attacked by Arikara Native Americans, who kill a number of the men. Glass then tries to lead the remainder of the group to safety, charting a new path to a U.S. fort. Unfortunately, he is soon mauled by a grizzly bear while hunting for food, and is horribly wounded. He is left in the care of roughneck John Fitzgerald (\u003ca href=\"https://www.allmovie.com/artist/tom-hardy-p301932\" class=\"name-link\"\u003eTom Hardy\u003c/a\u003e) and the young and inexperienced Jim Bridger (\u003ca href=\"https://www.allmovie.com/artist/will-poulter-p502624\" class=\"name-link\"\u003eWill Poulter\u003c/a\u003e), while Hawk watches on in horror. Fitzgerald betrays him and leaves him buried alive in a shallow grave, but Glass nurses himself back to health and sets out to seek revenge. \u003ca href=\"https://www.allmovie.com/artist/alejandro-gonz%C3%A1lez-i%C3%B1%C3%A1rritu-p297411\" class=\"name-link\"\u003eAlejandro González Iñárritu\u003c/a\u003e directed this pulse-pounding epic.        \u003c/div\u003e",
            "produced_by": "na",
            "directed_by": "Alejandro González Iñárritu"
        },
        {
            "id": 6,
            "crawled_at": "11/17/2019, 23:18:10",
            "description": "\n            007 (Daniel Craig) becomes M's only ally as MI6 comes under attack, and a mysterious new villain emerges with a diabolical plan. James Bond's latest mission has gone horribly awry, resulting in the exposure of several undercover agents, and an all-out attack on M16. Meanwhile, as M (Judi Dench) plans to relocate the agency, emerging Chairman of the Intelligence and Security Committee Mallory (Ralph Fiennes) raises concerns about her competence while attempting to usurp her position, and Q (Ben Whishaw) becomes a crucial ally. Now the only person who can restore M's reputation is 007. Operating in the dark with only field agent Eve (Naomie Harris) to guide him, the world's top secret agent works to root out an enigmatic criminal mastermind named Silva (Javier Bardem) as a major storm brews on the horizon. Albert Finney also stars in the 23rd installment of the long-running spy series. The film was directed by Sam Mendes (American Beauty, Revolutionary Road) and shot by acclaimed cinematographer Roger Deakins (True Grit, The Reader, The Assassination of Jesse James by the Coward Robert Ford).        ",
            "title": "Skyfall",
            "url": "https://www.allmovie.com/movie/skyfall-v532632",
            "poster": "https://cps-static.rovicorp.com/2/Open/Sony%20Pictures/Skyfall/_derived_jpg_q90_500x500_m0/SKYFAL_KATOS_0002.jpg",
            "raw_description": "\u003cdiv class=\"text\" itemprop=\"description\"\u003e\n            007 (\u003ca href=\"https://www.allmovie.com/artist/daniel-craig-p15549\" class=\"name-link\"\u003eDaniel Craig\u003c/a\u003e) becomes M's only ally as MI6 comes under attack, and a mysterious new villain emerges with a diabolical plan. James Bond's latest mission has gone horribly awry, resulting in the exposure of several undercover agents, and an all-out attack on M16. Meanwhile, as M (\u003ca href=\"https://www.allmovie.com/artist/judi-dench-p18570\" class=\"name-link\"\u003eJudi Dench\u003c/a\u003e) plans to relocate the agency, emerging Chairman of the Intelligence and Security Committee Mallory (\u003ca href=\"https://www.allmovie.com/artist/ralph-fiennes-p23390\" class=\"name-link\"\u003eRalph Fiennes\u003c/a\u003e) raises concerns about her competence while attempting to usurp her position, and Q (\u003ca href=\"https://www.allmovie.com/artist/ben-whishaw-p275426\" class=\"name-link\"\u003eBen Whishaw\u003c/a\u003e) becomes a crucial ally. Now the only person who can restore M's reputation is 007. Operating in the dark with only field agent Eve (\u003ca href=\"https://www.allmovie.com/artist/naomie-harris-p334461\" class=\"name-link\"\u003eNaomie Harris\u003c/a\u003e) to guide him, the world's top secret agent works to root out an enigmatic criminal mastermind named Silva (\u003ca href=\"https://www.allmovie.com/artist/javier-bardem-p3887\" class=\"name-link\"\u003eJavier Bardem\u003c/a\u003e) as a major storm brews on the horizon. \u003ca href=\"https://www.allmovie.com/artist/albert-finney-p23545\" class=\"name-link\"\u003eAlbert Finney\u003c/a\u003e also stars in the 23rd installment of the long-running spy series. The film was directed by \u003ca href=\"https://www.allmovie.com/artist/sam-mendes-p271193\" class=\"name-link\"\u003eSam Mendes\u003c/a\u003e (\u003ca href=\"https://www.allmovie.com/movie/american-beauty-v180738\" class=\"movie-link\"\u003eAmerican Beauty\u003c/a\u003e, \u003ca href=\"https://www.allmovie.com/movie/revolutionary-road-v395937\" class=\"movie-link\"\u003eRevolutionary Road\u003c/a\u003e) and shot by acclaimed cinematographer \u003ca href=\"https://www.allmovie.com/artist/roger-deakins-p87281\" class=\"name-link\"\u003eRoger Deakins\u003c/a\u003e (\u003ca href=\"https://www.allmovie.com/movie/true-grit-v483734\" class=\"movie-link\"\u003eTrue Grit\u003c/a\u003e, \u003ca href=\"https://www.allmovie.com/movie/the-reader-v413688\" class=\"movie-link\"\u003eThe Reader\u003c/a\u003e, \u003ca href=\"https://www.allmovie.com/movie/the-assassination-of-jesse-james-by-the-coward-robert-ford-v335202\" class=\"movie-link\"\u003eThe Assassination of Jesse James by the Coward Robert Ford\u003c/a\u003e).        \u003c/div\u003e",
            "produced_by": "na",
            "directed_by": "Sam Mendes"
        },
        {
            "id": 7,
            "crawled_at": "11/17/2019, 23:18:10",
            "description": "\n            Christopher Nolan steps back into the director's chair for this sequel to Batman Begins, which finds the titular superhero coming face to face with his greatest nemesis -- the dreaded Joker. Christian Bale returns to the role of Batman, Maggie Gyllenhaal takes over the role of Rachel Dawes (played by Katie Holmes in Batman Begins), and Brokeback Mountain star Heath Ledger dons the ghoulishly gleeful Joker makeup previously worn by Jack Nicholson and Cesar Romero. Just as it begins to appear as if Batman, Lt. James Gordon (Gary Oldman), and District Attorney Harvey Dent (Aaron Eckhart) are making headway in their tireless battle against the criminal element, a maniacal, wisecracking fiend plunges the streets of Gotham City into complete chaos.        ",
            "title": "The Dark Knight",
            "url": "https://www.allmovie.com/movie/the-dark-knight-v357349",
            "poster": "https://cps-static.rovicorp.com/2/Open/Warner%20Brothers%20Distribution/Movies/The%20Dark%20Knight/_derived_jpg_q90_500x500_m0/TheDarkKnight-BatmanPosterArt1CR.jpg",
            "raw_description": "\u003cdiv class=\"text\" itemprop=\"description\"\u003e\n            \u003ca href=\"https://www.allmovie.com/artist/christopher-nolan-p240025\" class=\"name-link\"\u003eChristopher Nolan\u003c/a\u003e steps back into the director's chair for this sequel to \u003ca href=\"https://www.allmovie.com/movie/batman-begins-v289465\" class=\"movie-link\"\u003eBatman Begins\u003c/a\u003e, which finds the titular superhero coming face to face with his greatest nemesis -- the dreaded Joker. \u003ca href=\"https://www.allmovie.com/artist/christian-bale-p3538\" class=\"name-link\"\u003eChristian Bale\u003c/a\u003e returns to the role of Batman, \u003ca href=\"https://www.allmovie.com/artist/maggie-gyllenhaal-p29409\" class=\"name-link\"\u003eMaggie Gyllenhaal\u003c/a\u003e takes over the role of Rachel Dawes (played by \u003ca href=\"https://www.allmovie.com/artist/katie-holmes-p225994\" class=\"name-link\"\u003eKatie Holmes\u003c/a\u003e in \u003ca href=\"https://www.allmovie.com/movie/batman-begins-v289465\" class=\"movie-link\"\u003eBatman Begins\u003c/a\u003e), and \u003ca href=\"https://www.allmovie.com/movie/brokeback-mountain-v301840\" class=\"movie-link\"\u003eBrokeback Mountain\u003c/a\u003e star \u003ca href=\"https://www.allmovie.com/artist/heath-ledger-p268296\" class=\"name-link\"\u003eHeath Ledger\u003c/a\u003e dons the ghoulishly gleeful Joker makeup previously worn by \u003ca href=\"https://www.allmovie.com/artist/jack-nicholson-p104455\" class=\"name-link\"\u003eJack Nicholson\u003c/a\u003e and \u003ca href=\"https://www.allmovie.com/artist/cesar-romero-p61318\" class=\"name-link\"\u003eCesar Romero\u003c/a\u003e. Just as it begins to appear as if Batman, Lt. James Gordon (\u003ca href=\"https://www.allmovie.com/artist/gary-oldman-p53946\" class=\"name-link\"\u003eGary Oldman\u003c/a\u003e), and District Attorney Harvey Dent (\u003ca href=\"https://www.allmovie.com/artist/aaron-eckhart-p223098\" class=\"name-link\"\u003eAaron Eckhart\u003c/a\u003e) are making headway in their tireless battle against the criminal element, a maniacal, wisecracking fiend plunges the streets of Gotham City into complete chaos.        \u003c/div\u003e",
            "produced_by": "na",
            "directed_by": "Christopher Nolan"
        },
        {
            "id": 8,
            "crawled_at": "11/17/2019, 23:18:10",
            "description": "\n            Christopher Nolan steps back into the director's chair for this sequel to Batman Begins, which finds the titular superhero coming face to face with his greatest nemesis -- the dreaded Joker. Christian Bale returns to the role of Batman, Maggie Gyllenhaal takes over the role of Rachel Dawes (played by Katie Holmes in Batman Begins), and Brokeback Mountain star Heath Ledger dons the ghoulishly gleeful Joker makeup previously worn by Jack Nicholson and Cesar Romero. Just as it begins to appear as if Batman, Lt. James Gordon (Gary Oldman), and District Attorney Harvey Dent (Aaron Eckhart) are making headway in their tireless battle against the criminal element, a maniacal, wisecracking fiend plunges the streets of Gotham City into complete chaos.        ",
            "title": "The Dark Knight",
            "url": "https://www.allmovie.com/movie/the-dark-knight-v357349",
            "poster": "https://cps-static.rovicorp.com/2/Open/Warner%20Brothers%20Distribution/Movies/The%20Dark%20Knight/_derived_jpg_q90_500x500_m0/TheDarkKnight-BatmanPosterArt1CR.jpg",
            "raw_description": "\u003cdiv class=\"text\" itemprop=\"description\"\u003e\n            \u003ca href=\"https://www.allmovie.com/artist/christopher-nolan-p240025\" class=\"name-link\"\u003eChristopher Nolan\u003c/a\u003e steps back into the director's chair for this sequel to \u003ca href=\"https://www.allmovie.com/movie/batman-begins-v289465\" class=\"movie-link\"\u003eBatman Begins\u003c/a\u003e, which finds the titular superhero coming face to face with his greatest nemesis -- the dreaded Joker. \u003ca href=\"https://www.allmovie.com/artist/christian-bale-p3538\" class=\"name-link\"\u003eChristian Bale\u003c/a\u003e returns to the role of Batman, \u003ca href=\"https://www.allmovie.com/artist/maggie-gyllenhaal-p29409\" class=\"name-link\"\u003eMaggie Gyllenhaal\u003c/a\u003e takes over the role of Rachel Dawes (played by \u003ca href=\"https://www.allmovie.com/artist/katie-holmes-p225994\" class=\"name-link\"\u003eKatie Holmes\u003c/a\u003e in \u003ca href=\"https://www.allmovie.com/movie/batman-begins-v289465\" class=\"movie-link\"\u003eBatman Begins\u003c/a\u003e), and \u003ca href=\"https://www.allmovie.com/movie/brokeback-mountain-v301840\" class=\"movie-link\"\u003eBrokeback Mountain\u003c/a\u003e star \u003ca href=\"https://www.allmovie.com/artist/heath-ledger-p268296\" class=\"name-link\"\u003eHeath Ledger\u003c/a\u003e dons the ghoulishly gleeful Joker makeup previously worn by \u003ca href=\"https://www.allmovie.com/artist/jack-nicholson-p104455\" class=\"name-link\"\u003eJack Nicholson\u003c/a\u003e and \u003ca href=\"https://www.allmovie.com/artist/cesar-romero-p61318\" class=\"name-link\"\u003eCesar Romero\u003c/a\u003e. Just as it begins to appear as if Batman, Lt. James Gordon (\u003ca href=\"https://www.allmovie.com/artist/gary-oldman-p53946\" class=\"name-link\"\u003eGary Oldman\u003c/a\u003e), and District Attorney Harvey Dent (\u003ca href=\"https://www.allmovie.com/artist/aaron-eckhart-p223098\" class=\"name-link\"\u003eAaron Eckhart\u003c/a\u003e) are making headway in their tireless battle against the criminal element, a maniacal, wisecracking fiend plunges the streets of Gotham City into complete chaos.        \u003c/div\u003e",
            "produced_by": "na",
            "directed_by": "Christopher Nolan"
        },
        {
            "id": 9,
            "crawled_at": "11/17/2019, 23:18:10",
            "description": "\n            Christopher Nolan steps back into the director's chair for this sequel to Batman Begins, which finds the titular superhero coming face to face with his greatest nemesis -- the dreaded Joker. Christian Bale returns to the role of Batman, Maggie Gyllenhaal takes over the role of Rachel Dawes (played by Katie Holmes in Batman Begins), and Brokeback Mountain star Heath Ledger dons the ghoulishly gleeful Joker makeup previously worn by Jack Nicholson and Cesar Romero. Just as it begins to appear as if Batman, Lt. James Gordon (Gary Oldman), and District Attorney Harvey Dent (Aaron Eckhart) are making headway in their tireless battle against the criminal element, a maniacal, wisecracking fiend plunges the streets of Gotham City into complete chaos.        ",
            "title": "The Dark Knight",
            "url": "https://www.allmovie.com/movie/the-dark-knight-v357349",
            "poster": "https://cps-static.rovicorp.com/2/Open/Warner%20Brothers%20Distribution/Movies/The%20Dark%20Knight/_derived_jpg_q90_500x500_m0/TheDarkKnight-BatmanPosterArt1CR.jpg",
            "raw_description": "\u003cdiv class=\"text\" itemprop=\"description\"\u003e\n            \u003ca href=\"https://www.allmovie.com/artist/christopher-nolan-p240025\" class=\"name-link\"\u003eChristopher Nolan\u003c/a\u003e steps back into the director's chair for this sequel to \u003ca href=\"https://www.allmovie.com/movie/batman-begins-v289465\" class=\"movie-link\"\u003eBatman Begins\u003c/a\u003e, which finds the titular superhero coming face to face with his greatest nemesis -- the dreaded Joker. \u003ca href=\"https://www.allmovie.com/artist/christian-bale-p3538\" class=\"name-link\"\u003eChristian Bale\u003c/a\u003e returns to the role of Batman, \u003ca href=\"https://www.allmovie.com/artist/maggie-gyllenhaal-p29409\" class=\"name-link\"\u003eMaggie Gyllenhaal\u003c/a\u003e takes over the role of Rachel Dawes (played by \u003ca href=\"https://www.allmovie.com/artist/katie-holmes-p225994\" class=\"name-link\"\u003eKatie Holmes\u003c/a\u003e in \u003ca href=\"https://www.allmovie.com/movie/batman-begins-v289465\" class=\"movie-link\"\u003eBatman Begins\u003c/a\u003e), and \u003ca href=\"https://www.allmovie.com/movie/brokeback-mountain-v301840\" class=\"movie-link\"\u003eBrokeback Mountain\u003c/a\u003e star \u003ca href=\"https://www.allmovie.com/artist/heath-ledger-p268296\" class=\"name-link\"\u003eHeath Ledger\u003c/a\u003e dons the ghoulishly gleeful Joker makeup previously worn by \u003ca href=\"https://www.allmovie.com/artist/jack-nicholson-p104455\" class=\"name-link\"\u003eJack Nicholson\u003c/a\u003e and \u003ca href=\"https://www.allmovie.com/artist/cesar-romero-p61318\" class=\"name-link\"\u003eCesar Romero\u003c/a\u003e. Just as it begins to appear as if Batman, Lt. James Gordon (\u003ca href=\"https://www.allmovie.com/artist/gary-oldman-p53946\" class=\"name-link\"\u003eGary Oldman\u003c/a\u003e), and District Attorney Harvey Dent (\u003ca href=\"https://www.allmovie.com/artist/aaron-eckhart-p223098\" class=\"name-link\"\u003eAaron Eckhart\u003c/a\u003e) are making headway in their tireless battle against the criminal element, a maniacal, wisecracking fiend plunges the streets of Gotham City into complete chaos.        \u003c/div\u003e",
            "produced_by": "na",
            "directed_by": "Christopher Nolan"
        },
        {
            "id": 10,
            "crawled_at": "11/17/2019, 23:18:10",
            "description": "\n            Christopher Nolan steps back into the director's chair for this sequel to Batman Begins, which finds the titular superhero coming face to face with his greatest nemesis -- the dreaded Joker. Christian Bale returns to the role of Batman, Maggie Gyllenhaal takes over the role of Rachel Dawes (played by Katie Holmes in Batman Begins), and Brokeback Mountain star Heath Ledger dons the ghoulishly gleeful Joker makeup previously worn by Jack Nicholson and Cesar Romero. Just as it begins to appear as if Batman, Lt. James Gordon (Gary Oldman), and District Attorney Harvey Dent (Aaron Eckhart) are making headway in their tireless battle against the criminal element, a maniacal, wisecracking fiend plunges the streets of Gotham City into complete chaos.        ",
            "title": "The Dark Knight",
            "url": "https://www.allmovie.com/movie/the-dark-knight-v357349",
            "poster": "https://cps-static.rovicorp.com/2/Open/Warner%20Brothers%20Distribution/Movies/The%20Dark%20Knight/_derived_jpg_q90_500x500_m0/TheDarkKnight-BatmanPosterArt1CR.jpg",
            "raw_description": "\u003cdiv class=\"text\" itemprop=\"description\"\u003e\n            \u003ca href=\"https://www.allmovie.com/artist/christopher-nolan-p240025\" class=\"name-link\"\u003eChristopher Nolan\u003c/a\u003e steps back into the director's chair for this sequel to \u003ca href=\"https://www.allmovie.com/movie/batman-begins-v289465\" class=\"movie-link\"\u003eBatman Begins\u003c/a\u003e, which finds the titular superhero coming face to face with his greatest nemesis -- the dreaded Joker. \u003ca href=\"https://www.allmovie.com/artist/christian-bale-p3538\" class=\"name-link\"\u003eChristian Bale\u003c/a\u003e returns to the role of Batman, \u003ca href=\"https://www.allmovie.com/artist/maggie-gyllenhaal-p29409\" class=\"name-link\"\u003eMaggie Gyllenhaal\u003c/a\u003e takes over the role of Rachel Dawes (played by \u003ca href=\"https://www.allmovie.com/artist/katie-holmes-p225994\" class=\"name-link\"\u003eKatie Holmes\u003c/a\u003e in \u003ca href=\"https://www.allmovie.com/movie/batman-begins-v289465\" class=\"movie-link\"\u003eBatman Begins\u003c/a\u003e), and \u003ca href=\"https://www.allmovie.com/movie/brokeback-mountain-v301840\" class=\"movie-link\"\u003eBrokeback Mountain\u003c/a\u003e star \u003ca href=\"https://www.allmovie.com/artist/heath-ledger-p268296\" class=\"name-link\"\u003eHeath Ledger\u003c/a\u003e dons the ghoulishly gleeful Joker makeup previously worn by \u003ca href=\"https://www.allmovie.com/artist/jack-nicholson-p104455\" class=\"name-link\"\u003eJack Nicholson\u003c/a\u003e and \u003ca href=\"https://www.allmovie.com/artist/cesar-romero-p61318\" class=\"name-link\"\u003eCesar Romero\u003c/a\u003e. Just as it begins to appear as if Batman, Lt. James Gordon (\u003ca href=\"https://www.allmovie.com/artist/gary-oldman-p53946\" class=\"name-link\"\u003eGary Oldman\u003c/a\u003e), and District Attorney Harvey Dent (\u003ca href=\"https://www.allmovie.com/artist/aaron-eckhart-p223098\" class=\"name-link\"\u003eAaron Eckhart\u003c/a\u003e) are making headway in their tireless battle against the criminal element, a maniacal, wisecracking fiend plunges the streets of Gotham City into complete chaos.        \u003c/div\u003e",
            "produced_by": "na",
            "directed_by": "Christopher Nolan"
        },
        {
            "id": 11,
            "crawled_at": "11/17/2019, 23:18:10",
            "description": "\n            Christopher Nolan steps back into the director's chair for this sequel to Batman Begins, which finds the titular superhero coming face to face with his greatest nemesis -- the dreaded Joker. Christian Bale returns to the role of Batman, Maggie Gyllenhaal takes over the role of Rachel Dawes (played by Katie Holmes in Batman Begins), and Brokeback Mountain star Heath Ledger dons the ghoulishly gleeful Joker makeup previously worn by Jack Nicholson and Cesar Romero. Just as it begins to appear as if Batman, Lt. James Gordon (Gary Oldman), and District Attorney Harvey Dent (Aaron Eckhart) are making headway in their tireless battle against the criminal element, a maniacal, wisecracking fiend plunges the streets of Gotham City into complete chaos.        ",
            "title": "The Dark Knight",
            "url": "https://www.allmovie.com/movie/the-dark-knight-v357349",
            "poster": "https://cps-static.rovicorp.com/2/Open/Warner%20Brothers%20Distribution/Movies/The%20Dark%20Knight/_derived_jpg_q90_500x500_m0/TheDarkKnight-BatmanPosterArt1CR.jpg",
            "raw_description": "\u003cdiv class=\"text\" itemprop=\"description\"\u003e\n            \u003ca href=\"https://www.allmovie.com/artist/christopher-nolan-p240025\" class=\"name-link\"\u003eChristopher Nolan\u003c/a\u003e steps back into the director's chair for this sequel to \u003ca href=\"https://www.allmovie.com/movie/batman-begins-v289465\" class=\"movie-link\"\u003eBatman Begins\u003c/a\u003e, which finds the titular superhero coming face to face with his greatest nemesis -- the dreaded Joker. \u003ca href=\"https://www.allmovie.com/artist/christian-bale-p3538\" class=\"name-link\"\u003eChristian Bale\u003c/a\u003e returns to the role of Batman, \u003ca href=\"https://www.allmovie.com/artist/maggie-gyllenhaal-p29409\" class=\"name-link\"\u003eMaggie Gyllenhaal\u003c/a\u003e takes over the role of Rachel Dawes (played by \u003ca href=\"https://www.allmovie.com/artist/katie-holmes-p225994\" class=\"name-link\"\u003eKatie Holmes\u003c/a\u003e in \u003ca href=\"https://www.allmovie.com/movie/batman-begins-v289465\" class=\"movie-link\"\u003eBatman Begins\u003c/a\u003e), and \u003ca href=\"https://www.allmovie.com/movie/brokeback-mountain-v301840\" class=\"movie-link\"\u003eBrokeback Mountain\u003c/a\u003e star \u003ca href=\"https://www.allmovie.com/artist/heath-ledger-p268296\" class=\"name-link\"\u003eHeath Ledger\u003c/a\u003e dons the ghoulishly gleeful Joker makeup previously worn by \u003ca href=\"https://www.allmovie.com/artist/jack-nicholson-p104455\" class=\"name-link\"\u003eJack Nicholson\u003c/a\u003e and \u003ca href=\"https://www.allmovie.com/artist/cesar-romero-p61318\" class=\"name-link\"\u003eCesar Romero\u003c/a\u003e. Just as it begins to appear as if Batman, Lt. James Gordon (\u003ca href=\"https://www.allmovie.com/artist/gary-oldman-p53946\" class=\"name-link\"\u003eGary Oldman\u003c/a\u003e), and District Attorney Harvey Dent (\u003ca href=\"https://www.allmovie.com/artist/aaron-eckhart-p223098\" class=\"name-link\"\u003eAaron Eckhart\u003c/a\u003e) are making headway in their tireless battle against the criminal element, a maniacal, wisecracking fiend plunges the streets of Gotham City into complete chaos.        \u003c/div\u003e",
            "produced_by": "na",
            "directed_by": "Christopher Nolan"
        },
        {
            "id": 12,
            "crawled_at": "11/17/2019, 23:18:10",
            "description": "\n            Christopher Nolan steps back into the director's chair for this sequel to Batman Begins, which finds the titular superhero coming face to face with his greatest nemesis -- the dreaded Joker. Christian Bale returns to the role of Batman, Maggie Gyllenhaal takes over the role of Rachel Dawes (played by Katie Holmes in Batman Begins), and Brokeback Mountain star Heath Ledger dons the ghoulishly gleeful Joker makeup previously worn by Jack Nicholson and Cesar Romero. Just as it begins to appear as if Batman, Lt. James Gordon (Gary Oldman), and District Attorney Harvey Dent (Aaron Eckhart) are making headway in their tireless battle against the criminal element, a maniacal, wisecracking fiend plunges the streets of Gotham City into complete chaos.        ",
            "title": "The Dark Knight",
            "url": "https://www.allmovie.com/movie/the-dark-knight-v357349",
            "poster": "https://cps-static.rovicorp.com/2/Open/Warner%20Brothers%20Distribution/Movies/The%20Dark%20Knight/_derived_jpg_q90_500x500_m0/TheDarkKnight-BatmanPosterArt1CR.jpg",
            "raw_description": "\u003cdiv class=\"text\" itemprop=\"description\"\u003e\n            \u003ca href=\"https://www.allmovie.com/artist/christopher-nolan-p240025\" class=\"name-link\"\u003eChristopher Nolan\u003c/a\u003e steps back into the director's chair for this sequel to \u003ca href=\"https://www.allmovie.com/movie/batman-begins-v289465\" class=\"movie-link\"\u003eBatman Begins\u003c/a\u003e, which finds the titular superhero coming face to face with his greatest nemesis -- the dreaded Joker. \u003ca href=\"https://www.allmovie.com/artist/christian-bale-p3538\" class=\"name-link\"\u003eChristian Bale\u003c/a\u003e returns to the role of Batman, \u003ca href=\"https://www.allmovie.com/artist/maggie-gyllenhaal-p29409\" class=\"name-link\"\u003eMaggie Gyllenhaal\u003c/a\u003e takes over the role of Rachel Dawes (played by \u003ca href=\"https://www.allmovie.com/artist/katie-holmes-p225994\" class=\"name-link\"\u003eKatie Holmes\u003c/a\u003e in \u003ca href=\"https://www.allmovie.com/movie/batman-begins-v289465\" class=\"movie-link\"\u003eBatman Begins\u003c/a\u003e), and \u003ca href=\"https://www.allmovie.com/movie/brokeback-mountain-v301840\" class=\"movie-link\"\u003eBrokeback Mountain\u003c/a\u003e star \u003ca href=\"https://www.allmovie.com/artist/heath-ledger-p268296\" class=\"name-link\"\u003eHeath Ledger\u003c/a\u003e dons the ghoulishly gleeful Joker makeup previously worn by \u003ca href=\"https://www.allmovie.com/artist/jack-nicholson-p104455\" class=\"name-link\"\u003eJack Nicholson\u003c/a\u003e and \u003ca href=\"https://www.allmovie.com/artist/cesar-romero-p61318\" class=\"name-link\"\u003eCesar Romero\u003c/a\u003e. Just as it begins to appear as if Batman, Lt. James Gordon (\u003ca href=\"https://www.allmovie.com/artist/gary-oldman-p53946\" class=\"name-link\"\u003eGary Oldman\u003c/a\u003e), and District Attorney Harvey Dent (\u003ca href=\"https://www.allmovie.com/artist/aaron-eckhart-p223098\" class=\"name-link\"\u003eAaron Eckhart\u003c/a\u003e) are making headway in their tireless battle against the criminal element, a maniacal, wisecracking fiend plunges the streets of Gotham City into complete chaos.        \u003c/div\u003e",
            "produced_by": "na",
            "directed_by": "Christopher Nolan"
        },
        {
            "id": 13,
            "crawled_at": "11/17/2019, 23:18:10",
            "description": "\n            Christopher Nolan steps back into the director's chair for this sequel to Batman Begins, which finds the titular superhero coming face to face with his greatest nemesis -- the dreaded Joker. Christian Bale returns to the role of Batman, Maggie Gyllenhaal takes over the role of Rachel Dawes (played by Katie Holmes in Batman Begins), and Brokeback Mountain star Heath Ledger dons the ghoulishly gleeful Joker makeup previously worn by Jack Nicholson and Cesar Romero. Just as it begins to appear as if Batman, Lt. James Gordon (Gary Oldman), and District Attorney Harvey Dent (Aaron Eckhart) are making headway in their tireless battle against the criminal element, a maniacal, wisecracking fiend plunges the streets of Gotham City into complete chaos.        ",
            "title": "The Dark Knight",
            "url": "https://www.allmovie.com/movie/the-dark-knight-v357349",
            "poster": "https://cps-static.rovicorp.com/2/Open/Warner%20Brothers%20Distribution/Movies/The%20Dark%20Knight/_derived_jpg_q90_500x500_m0/TheDarkKnight-BatmanPosterArt1CR.jpg",
            "raw_description": "\u003cdiv class=\"text\" itemprop=\"description\"\u003e\n            \u003ca href=\"https://www.allmovie.com/artist/christopher-nolan-p240025\" class=\"name-link\"\u003eChristopher Nolan\u003c/a\u003e steps back into the director's chair for this sequel to \u003ca href=\"https://www.allmovie.com/movie/batman-begins-v289465\" class=\"movie-link\"\u003eBatman Begins\u003c/a\u003e, which finds the titular superhero coming face to face with his greatest nemesis -- the dreaded Joker. \u003ca href=\"https://www.allmovie.com/artist/christian-bale-p3538\" class=\"name-link\"\u003eChristian Bale\u003c/a\u003e returns to the role of Batman, \u003ca href=\"https://www.allmovie.com/artist/maggie-gyllenhaal-p29409\" class=\"name-link\"\u003eMaggie Gyllenhaal\u003c/a\u003e takes over the role of Rachel Dawes (played by \u003ca href=\"https://www.allmovie.com/artist/katie-holmes-p225994\" class=\"name-link\"\u003eKatie Holmes\u003c/a\u003e in \u003ca href=\"https://www.allmovie.com/movie/batman-begins-v289465\" class=\"movie-link\"\u003eBatman Begins\u003c/a\u003e), and \u003ca href=\"https://www.allmovie.com/movie/brokeback-mountain-v301840\" class=\"movie-link\"\u003eBrokeback Mountain\u003c/a\u003e star \u003ca href=\"https://www.allmovie.com/artist/heath-ledger-p268296\" class=\"name-link\"\u003eHeath Ledger\u003c/a\u003e dons the ghoulishly gleeful Joker makeup previously worn by \u003ca href=\"https://www.allmovie.com/artist/jack-nicholson-p104455\" class=\"name-link\"\u003eJack Nicholson\u003c/a\u003e and \u003ca href=\"https://www.allmovie.com/artist/cesar-romero-p61318\" class=\"name-link\"\u003eCesar Romero\u003c/a\u003e. Just as it begins to appear as if Batman, Lt. James Gordon (\u003ca href=\"https://www.allmovie.com/artist/gary-oldman-p53946\" class=\"name-link\"\u003eGary Oldman\u003c/a\u003e), and District Attorney Harvey Dent (\u003ca href=\"https://www.allmovie.com/artist/aaron-eckhart-p223098\" class=\"name-link\"\u003eAaron Eckhart\u003c/a\u003e) are making headway in their tireless battle against the criminal element, a maniacal, wisecracking fiend plunges the streets of Gotham City into complete chaos.        \u003c/div\u003e",
            "produced_by": "na",
            "directed_by": "Christopher Nolan"
        },
        {
            "id": 14,
            "crawled_at": "11/17/2019, 23:18:10",
            "description": "\n            Christopher Nolan steps back into the director's chair for this sequel to Batman Begins, which finds the titular superhero coming face to face with his greatest nemesis -- the dreaded Joker. Christian Bale returns to the role of Batman, Maggie Gyllenhaal takes over the role of Rachel Dawes (played by Katie Holmes in Batman Begins), and Brokeback Mountain star Heath Ledger dons the ghoulishly gleeful Joker makeup previously worn by Jack Nicholson and Cesar Romero. Just as it begins to appear as if Batman, Lt. James Gordon (Gary Oldman), and District Attorney Harvey Dent (Aaron Eckhart) are making headway in their tireless battle against the criminal element, a maniacal, wisecracking fiend plunges the streets of Gotham City into complete chaos.        ",
            "title": "The Dark Knight",
            "url": "https://www.allmovie.com/movie/the-dark-knight-v357349",
            "poster": "https://cps-static.rovicorp.com/2/Open/Warner%20Brothers%20Distribution/Movies/The%20Dark%20Knight/_derived_jpg_q90_500x500_m0/TheDarkKnight-BatmanPosterArt1CR.jpg",
            "raw_description": "\u003cdiv class=\"text\" itemprop=\"description\"\u003e\n            \u003ca href=\"https://www.allmovie.com/artist/christopher-nolan-p240025\" class=\"name-link\"\u003eChristopher Nolan\u003c/a\u003e steps back into the director's chair for this sequel to \u003ca href=\"https://www.allmovie.com/movie/batman-begins-v289465\" class=\"movie-link\"\u003eBatman Begins\u003c/a\u003e, which finds the titular superhero coming face to face with his greatest nemesis -- the dreaded Joker. \u003ca href=\"https://www.allmovie.com/artist/christian-bale-p3538\" class=\"name-link\"\u003eChristian Bale\u003c/a\u003e returns to the role of Batman, \u003ca href=\"https://www.allmovie.com/artist/maggie-gyllenhaal-p29409\" class=\"name-link\"\u003eMaggie Gyllenhaal\u003c/a\u003e takes over the role of Rachel Dawes (played by \u003ca href=\"https://www.allmovie.com/artist/katie-holmes-p225994\" class=\"name-link\"\u003eKatie Holmes\u003c/a\u003e in \u003ca href=\"https://www.allmovie.com/movie/batman-begins-v289465\" class=\"movie-link\"\u003eBatman Begins\u003c/a\u003e), and \u003ca href=\"https://www.allmovie.com/movie/brokeback-mountain-v301840\" class=\"movie-link\"\u003eBrokeback Mountain\u003c/a\u003e star \u003ca href=\"https://www.allmovie.com/artist/heath-ledger-p268296\" class=\"name-link\"\u003eHeath Ledger\u003c/a\u003e dons the ghoulishly gleeful Joker makeup previously worn by \u003ca href=\"https://www.allmovie.com/artist/jack-nicholson-p104455\" class=\"name-link\"\u003eJack Nicholson\u003c/a\u003e and \u003ca href=\"https://www.allmovie.com/artist/cesar-romero-p61318\" class=\"name-link\"\u003eCesar Romero\u003c/a\u003e. Just as it begins to appear as if Batman, Lt. James Gordon (\u003ca href=\"https://www.allmovie.com/artist/gary-oldman-p53946\" class=\"name-link\"\u003eGary Oldman\u003c/a\u003e), and District Attorney Harvey Dent (\u003ca href=\"https://www.allmovie.com/artist/aaron-eckhart-p223098\" class=\"name-link\"\u003eAaron Eckhart\u003c/a\u003e) are making headway in their tireless battle against the criminal element, a maniacal, wisecracking fiend plunges the streets of Gotham City into complete chaos.        \u003c/div\u003e",
            "produced_by": "na",
            "directed_by": "Christopher Nolan"
        },
        {
            "id": 15,
            "crawled_at": "11/17/2019, 23:18:10",
            "description": "\n            Christopher Nolan steps back into the director's chair for this sequel to Batman Begins, which finds the titular superhero coming face to face with his greatest nemesis -- the dreaded Joker. Christian Bale returns to the role of Batman, Maggie Gyllenhaal takes over the role of Rachel Dawes (played by Katie Holmes in Batman Begins), and Brokeback Mountain star Heath Ledger dons the ghoulishly gleeful Joker makeup previously worn by Jack Nicholson and Cesar Romero. Just as it begins to appear as if Batman, Lt. James Gordon (Gary Oldman), and District Attorney Harvey Dent (Aaron Eckhart) are making headway in their tireless battle against the criminal element, a maniacal, wisecracking fiend plunges the streets of Gotham City into complete chaos.        ",
            "title": "The Dark Knight",
            "url": "https://www.allmovie.com/movie/the-dark-knight-v357349",
            "poster": "https://cps-static.rovicorp.com/2/Open/Warner%20Brothers%20Distribution/Movies/The%20Dark%20Knight/_derived_jpg_q90_500x500_m0/TheDarkKnight-BatmanPosterArt1CR.jpg",
            "raw_description": "\u003cdiv class=\"text\" itemprop=\"description\"\u003e\n            \u003ca href=\"https://www.allmovie.com/artist/christopher-nolan-p240025\" class=\"name-link\"\u003eChristopher Nolan\u003c/a\u003e steps back into the director's chair for this sequel to \u003ca href=\"https://www.allmovie.com/movie/batman-begins-v289465\" class=\"movie-link\"\u003eBatman Begins\u003c/a\u003e, which finds the titular superhero coming face to face with his greatest nemesis -- the dreaded Joker. \u003ca href=\"https://www.allmovie.com/artist/christian-bale-p3538\" class=\"name-link\"\u003eChristian Bale\u003c/a\u003e returns to the role of Batman, \u003ca href=\"https://www.allmovie.com/artist/maggie-gyllenhaal-p29409\" class=\"name-link\"\u003eMaggie Gyllenhaal\u003c/a\u003e takes over the role of Rachel Dawes (played by \u003ca href=\"https://www.allmovie.com/artist/katie-holmes-p225994\" class=\"name-link\"\u003eKatie Holmes\u003c/a\u003e in \u003ca href=\"https://www.allmovie.com/movie/batman-begins-v289465\" class=\"movie-link\"\u003eBatman Begins\u003c/a\u003e), and \u003ca href=\"https://www.allmovie.com/movie/brokeback-mountain-v301840\" class=\"movie-link\"\u003eBrokeback Mountain\u003c/a\u003e star \u003ca href=\"https://www.allmovie.com/artist/heath-ledger-p268296\" class=\"name-link\"\u003eHeath Ledger\u003c/a\u003e dons the ghoulishly gleeful Joker makeup previously worn by \u003ca href=\"https://www.allmovie.com/artist/jack-nicholson-p104455\" class=\"name-link\"\u003eJack Nicholson\u003c/a\u003e and \u003ca href=\"https://www.allmovie.com/artist/cesar-romero-p61318\" class=\"name-link\"\u003eCesar Romero\u003c/a\u003e. Just as it begins to appear as if Batman, Lt. James Gordon (\u003ca href=\"https://www.allmovie.com/artist/gary-oldman-p53946\" class=\"name-link\"\u003eGary Oldman\u003c/a\u003e), and District Attorney Harvey Dent (\u003ca href=\"https://www.allmovie.com/artist/aaron-eckhart-p223098\" class=\"name-link\"\u003eAaron Eckhart\u003c/a\u003e) are making headway in their tireless battle against the criminal element, a maniacal, wisecracking fiend plunges the streets of Gotham City into complete chaos.        \u003c/div\u003e",
            "produced_by": "na",
            "directed_by": "Christopher Nolan"
        },
        {
            "id": 16,
            "crawled_at": "11/17/2019, 23:18:10",
            "description": "\n            Christopher Nolan steps back into the director's chair for this sequel to Batman Begins, which finds the titular superhero coming face to face with his greatest nemesis -- the dreaded Joker. Christian Bale returns to the role of Batman, Maggie Gyllenhaal takes over the role of Rachel Dawes (played by Katie Holmes in Batman Begins), and Brokeback Mountain star Heath Ledger dons the ghoulishly gleeful Joker makeup previously worn by Jack Nicholson and Cesar Romero. Just as it begins to appear as if Batman, Lt. James Gordon (Gary Oldman), and District Attorney Harvey Dent (Aaron Eckhart) are making headway in their tireless battle against the criminal element, a maniacal, wisecracking fiend plunges the streets of Gotham City into complete chaos.        ",
            "title": "The Dark Knight",
            "url": "https://www.allmovie.com/movie/the-dark-knight-v357349",
            "poster": "https://cps-static.rovicorp.com/2/Open/Warner%20Brothers%20Distribution/Movies/The%20Dark%20Knight/_derived_jpg_q90_500x500_m0/TheDarkKnight-BatmanPosterArt1CR.jpg",
            "raw_description": "\u003cdiv class=\"text\" itemprop=\"description\"\u003e\n            \u003ca href=\"https://www.allmovie.com/artist/christopher-nolan-p240025\" class=\"name-link\"\u003eChristopher Nolan\u003c/a\u003e steps back into the director's chair for this sequel to \u003ca href=\"https://www.allmovie.com/movie/batman-begins-v289465\" class=\"movie-link\"\u003eBatman Begins\u003c/a\u003e, which finds the titular superhero coming face to face with his greatest nemesis -- the dreaded Joker. \u003ca href=\"https://www.allmovie.com/artist/christian-bale-p3538\" class=\"name-link\"\u003eChristian Bale\u003c/a\u003e returns to the role of Batman, \u003ca href=\"https://www.allmovie.com/artist/maggie-gyllenhaal-p29409\" class=\"name-link\"\u003eMaggie Gyllenhaal\u003c/a\u003e takes over the role of Rachel Dawes (played by \u003ca href=\"https://www.allmovie.com/artist/katie-holmes-p225994\" class=\"name-link\"\u003eKatie Holmes\u003c/a\u003e in \u003ca href=\"https://www.allmovie.com/movie/batman-begins-v289465\" class=\"movie-link\"\u003eBatman Begins\u003c/a\u003e), and \u003ca href=\"https://www.allmovie.com/movie/brokeback-mountain-v301840\" class=\"movie-link\"\u003eBrokeback Mountain\u003c/a\u003e star \u003ca href=\"https://www.allmovie.com/artist/heath-ledger-p268296\" class=\"name-link\"\u003eHeath Ledger\u003c/a\u003e dons the ghoulishly gleeful Joker makeup previously worn by \u003ca href=\"https://www.allmovie.com/artist/jack-nicholson-p104455\" class=\"name-link\"\u003eJack Nicholson\u003c/a\u003e and \u003ca href=\"https://www.allmovie.com/artist/cesar-romero-p61318\" class=\"name-link\"\u003eCesar Romero\u003c/a\u003e. Just as it begins to appear as if Batman, Lt. James Gordon (\u003ca href=\"https://www.allmovie.com/artist/gary-oldman-p53946\" class=\"name-link\"\u003eGary Oldman\u003c/a\u003e), and District Attorney Harvey Dent (\u003ca href=\"https://www.allmovie.com/artist/aaron-eckhart-p223098\" class=\"name-link\"\u003eAaron Eckhart\u003c/a\u003e) are making headway in their tireless battle against the criminal element, a maniacal, wisecracking fiend plunges the streets of Gotham City into complete chaos.        \u003c/div\u003e",
            "produced_by": "na",
            "directed_by": "Christopher Nolan"
        },

    ])
    
}